services:
    qbittorrent-bot:
        build: .
        image: 'meanii/qbittorrent-bot:latest'
        container_name: qbittorrent-bot
        restart: unless-stopped
        volumes:
            - '/home/user/docker/QBittorrentBot:/app/config:rw'
            - 'config.json:/app/config/config.json:rw'
